// Code generated by "stringer -type=Action"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nothing-0]
	_ = x[Quit-1]
	_ = x[NewGame-2]
	_ = x[ShowCredits-3]
	_ = x[GameOver-4]
}

const _Action_name = "NothingQuitNewGameShowCreditsGameOver"

var _Action_index = [...]uint8{0, 7, 11, 18, 29, 37}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
